# Generated by Django 2.2.6 on 2019-11-02 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word_learn', '0002_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnlikeList',
            new_name='WeakList',
        ),
    ]
