# Generated by Django 2.2.6 on 2019-11-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learn', '0003_auto_20191102_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='weak',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WeakList',
        ),
    ]
